---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase
spec:
  ports:
  - name: default
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: metabase
  type: NodePort
